// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:cfc91cdb-2e7d-4d94-9812-ee555ba41ad5",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_6We96vE6C",
    "aws_user_pools_web_client_id": "786nfu4mf9psheej31as80okjb",
    "oauth": {},
    "aws_content_delivery_bucket": "quster-dev-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-northeast-2",
    "aws_content_delivery_url": "http://quster-dev-hostingbucket-dev.s3-website.ap-northeast-2.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://rnphusozfrfajls5w7xjd5p5va.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};


export default awsmobile;
